
[window]
position = "None" # Managed by the window manager (default)
opacity = 0.95

[scrolling]
history = 10000

[font]
normal = {family = "DejaVu Sans Mono", style = "Regular"}
size = 11.0

[general]
import = ["~/.config/alacritty/alacritty-theme/themes/onedark.toml"]

