" All system-wide defaults are set in $VIMRUNTIME/archlinux.vim (usually just
" /usr/share/vim/vimfiles/archlinux.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vimrc), since archlinux.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing archlinux.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages.
runtime! archlinux.vim

" If you prefer the old-style vim functionalty, add 'runtime! vimrc_example.vim'
" Or better yet, read /usr/share/vim/vim74/vimrc_example.vim or the vim manual
" and configure vim to your own liking!

" BEGIN OF JUSTIN'S SYSTEM-WIDE CONFIGURATION
" Enable vundle
set nocompatible  " required, be iMproved!
filetype off      " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

Plugin 'gmarik/Vundle.vim'   " let Vundle manage Vundle, required
Plugin 'scrooloose/nerdtree'
Plugin 'vim-fugitive'        " Git integration
Plugin 'openscad.vim'        " .scad ftplugin

" Plugins required for vim-orgmode
Plugin 'jceb/vim-orgmode'
Plugin 'speeddating.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList          - list configured plugins
" :PluginInstall(!)    - install (update) plugins
" :PluginSearch(!) foo - search (or refresh cache first) for foo
" :PluginClean(!)      - confirm (or auto-approve) removal of unused plugins


" Set tab and indent behaviour
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set cindent
set autoindent

" Turn on syntax highlighting
syntax on

" Set colorscheme
colorscheme desert

" Enable line numbering
set nu!

" No text wrap by default
set nowrap

" Set leader keys for use with vim-orgmode
let mapleader=","
let maplocalleader=","

" Allow saving of files as sudo 
cmap w!! w !sudo tee > /dev/null %
