" Set some requirements for Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim

" Declare all the desired plugins
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
Plugin 'majutsushi/tagbar'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'ctrlpvim/ctrlp.vim'
call vundle#end()

filetype plugin indent on

" Configure vim-airline
set laststatus=2
set ttimeoutlen=10
if !exists('g:airline_symbols')
  let g:airline_symbols = {}
endif
let g:airline_left_sep = ''
let g:airline_right_sep = ''
let g:airline_symbols.linenr = '¶'
"let g:airline_symbols.branch = '⎇'
let g:airline_symbols.branch = 'b'

" Configure syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Configure ctrlp fuzzy finder
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'

" Configure tab and indent settings
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4
set cindent
set autoindent

" Turn on syntax highlighting
syntax on

" Set colorscheme
set t_Co=256
set background=dark
colorscheme desert
set colorcolumn=80
highlight ColorColumn ctermbg=darkgray

" Move .viminfo file
set viminfo+=n~/.vim/viminfo

" Enable line numbering
set nu!

" No text wrap by default
set nowrap

" Allow saving of files as sudo
cmap w!! w !sudo tee > /dev/null %

" Configure keybinds
nnoremap <F4> :make!<cr>
nnoremap <F5> :make run!<cr>
nnoremap <F8> :TagbarToggle<cr>
nnoremap <F1> :NERDTreeToggle<cr>

