#!/bin/sh
# Script run after every switch of autorandr

# Move mouse to the middle of the screen
resolution=$(xrandr --listactivemonitors | grep "*" | awk '{ print $3 }')
screenwidth=$(echo $resolution | sed 's/^\([^/]*\).*/\1/')
screenheight=$(echo $resolution | sed 's/^.*x\([^/]*\).*/\1/')
nx=$((screenwidth/2))
ny=$((screenheight/2))
xdotool mousemove $nx $ny

# TODO remove? Doesn't apply to awesome wm?
# Refresh the background to fit the new screen
$HOME/.fehbg
