;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; tinman16-theme.el
;; Justin R. St-Amant, 2017-02-18
;;
;; Commentary:
;;
;; NEEDS DOCUMENTATION; SCRAP ALL OF THIS!
;;
;; This file is strongly based off Kaleb Elwert's work in the
;; base16-emacs repository, https://github.com/belak/base16-emacs/
;;
;; The main reason for using the code from the base16-emacs repository
;; is for documentation purposes. I didn't feel like the code in the
;; repository was properly documented, so I rewrote it to my needs and
;; standards.
;;
;; The other reason for using the code was for my own
;; customization. The themes generated by the base16-emacs repository
;; worked, but the settings made org-mode and many other faces too
;; un-coordinated. UNFINISHED
;;
;; UNFINISHED.
;;
;; This file does not actually provide a theme that can be loaded
;; using M-x load-theme. I will need to look more into this and see
;; what I want to do.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Variables / Color sets / Faces
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defvar base16-shell-colors
  '(:base01  "brightgreen"
    :base02  "brightyellow"
    :base03  "brightblack"
    :base04  "brightblue"
    :base05  "white"
    :base06  "brightmagenta"
    :base07  "brightwhite"

    :black   "black"
    :red     "red"
    :green   "green"
    :yellow  "yellow"
    :blue    "blue"
    :magenta "magenta"
    :cyan    "cyan"
    :white   "white"

    :orange  "yellow"
    :brown   "red")
  "Safe Base16 colors for use in a terminal.
i.e. with a limited color palette.

UNIMPLEMENTED YET?")

(defvar custom-faces
  '((default :foreground white :background black)
    (link :foreground cyan)
    (font-lock-comment-face  :foreground cyan)
    (font-lock-constant-face :foreground orange)
    (font-lock-keyword-face  :foreground magenta)
    (font-lock-string-face   :foreground green)
    (outline-1 :foreground blue)
    (outline-2 :foreground yellow)
    (org-todo :foreground red)
    (org-done :foreground green)
    ;; (org-agenda-structure :foreground base0D)
    ;; (org-special-keyword :foreground base0C)
    ;; (org-link :foreground base0C)
    (term-color-black :foreground black)
    (term-color-red :foreground red)
    (term-color-green :foreground green)
    (term-color-yellow :foreground yellow)
    (term-color-blue :foreground blue)
    (term-color-magenta :foreground magenta)
    (term-color-cyan :foreground cyan)
    (term-color-white :foreground white))
    ;; (highlight :background base03)
    ;; (ledger-font-payee-uncleared-face :foreground base08)
    ;; (ledger-font-other-face :foreground base04)
  ;; (ledger-font-pending-face :foreground base09))
  "A list of faces, and the attributes to apply to them.

The format of this list is as follows:
(face . attributes)
(face . attributes)
(face . attributes)
...

Where face is the name of the face, and attributes is a plist of
attributes taking the form:
(attribute value attribute value ... )

Example:
(:foreground \"#00ff00\" :background \"#000000\")

See macro `defface', and look into \"face specs\" or \"face
attributes\" for more info.

Possible attributes can be found in Info node `(elisp)Face Attributes'.")

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Theme-generation functions
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(defun initialize-theme (theme colors faces)
  "DOCUMENTATION INCOMPLETE"
  ;;PROBLEM: custom-theme-set-faces needs the faces in seperate ARGS,
  ;;not in a single list, as I'm making with 'apply-face-spec
  (apply
   'custom-theme-set-faces
   theme
   (mapcar
    (lambda (face)
      (apply-face-spec colors face))
    faces)))

(defun apply-face-spec (colors face)
  "DOCUMENTATION INCOMPLETE Applies a face spec to each face in
`FACES', according to a list of `COLORS' to use. For use with
`custom-set-faces' or `custom-theme-set-face'. From a list
containing the face symbol, and a plist of attributes.  Returns a
list of elements of the form ___"
  (let ((name       (car face))
        (attributes (cdr face)))
    ;; THIS CAN BE SHORTENED
    (list name (list (list '((min-colors 256)) (sub-color-keys attributes colors))
                     (list t                   (sub-color-keys attributes colors))))))

(defun sub-color-keys (attributes colors)
  "DOCUMENTATION INCOMPLETE

Converts custom color names in a plist to color strings.

Example: (:foreground red) gets converted to (:foreground \"#ff0000\")

Does not support constants??

Note: Potentially does not work with :box or :underline
attributes."
  (let ((output))
    (while attributes
      (let* ((key   (car attributes))
             (value (cadr attributes))
             (color-key (if (symbolp value) (intern (concat ":" (symbol-name value)) nil)))
             (color (plist-get colors color-key)))
        (cond (color
               (setq output (append output (list key color))))
              (t
               (setq output (append output (list key value)))))
        ;; Proceed to the next set of attributes
        (setq attributes (cddr attributes))))
      output))

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(provide 'tinman16-theme)
