" Set colorscheme and highlight line and column
colorscheme habamax " 'slate' is a good alternative
set colorcolumn=80
set cursorline

" Configure tab and indent settings
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2

" Set tab-completion preferences
" Similar to bash-style autocomplete, but lets you cycle through choices
set wildmode=longest,list,full

" Turn on syntax highlighting
syntax on

" Move .viminfo file
set viminfo+=n~/.vim/viminfo

" Enable line numbering
set number

" No text wrap by default
set nowrap
set linebreak " If wrap is on: logical linebreaks occur at the end of words
set textwidth=80

" Tab settings by filetype
autocmd Filetype c setlocal ts=4 sts=4 sw=4
autocmd Filetype cpp setlocal ts=4 sts=4 sw=4

" Keybindings
nnoremap <F12> :set cursorline!<cr>
