#!/bin/sh

# Source this file in login shells and non-login shells to gain access
# to your environment variables

# Set XDG variables
export XDG_CONFIG_HOME="$HOME/.config"

# Set vim as primary editor
export EDITOR='vim'
export VISUAL='vim'

# Explicitly set pager to less
export PAGER='less'

# Set other non-standard variables for my own scripts
export BROWSER='google-chrome-stable' # Currently unused
export FILE_MANAGER='pcmanfm' # Currently unused
export LAUNCHER='rofi -show drun'
export TERMINAL='alacritty'

# Custom PATH additions
export PATH="$PATH:~/bin"
export PATH="$PATH:~/.emacs.d/bin" # for Doom Emacs
export PATH="$PATH:~/.cargo/bin" # for installed Rust crate executables

# SSH setup (ssh-agent.service must be running)
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
