#!/bin/sh

# Source this file in login shells and non-login shells to gain access
# to your environment variables

# Set XDG variables
export XDG_CONFIG_HOME="$HOME/.config"

# Set vim as primary editor
export EDITOR='vim'
export VISUAL='vim'

# Explicitly set pager to less
export PAGER='less'

# Set other non-standard variables for my own scripts
export BROWSER='google-chrome-stable' # Currently unused
export FILE_MANAGER='pcmanfm' # Currently unused
export LAUNCHER='dmenu_run'
export TERMINAL='kitty'

# Custom PATH additions
export PATH=$PATH:~/bin
