#!/bin/sh
# Clear any existing rules
bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config top_padding          0
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config border_width         1
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Insync state=floating
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser desktop='^2'

bspc rule -a Emacs state=tiled
bspc rule -a Zathura state=tiled

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config external_rules_command $HOME/.config/bspwm/external_rules.sh

# Colors and appearance
# Blue primary accent
primary=$(xrdb -query | grep 'color4:' | awk '{print $2}')
fore=$(xrdb -query | grep 'color7:' | awk '{print $2}')
fore_alt=$(xrdb -query | grep 'color15:' | awk '{print $2}')
back=$(xrdb -query | grep 'color0:' | awk '{print $2}')
back_alt=$(xrdb -query | grep 'color8:' | awk '{print $2}')
bspc config active_border_color  $primary
bspc config focused_border_color $primary
bspc config normal_border_color  $back
# Fix cursor from 'X' to a left pointer
xsetroot -cursor_name left_ptr

# Autostart applications related to bspwm
sxhkd -c $HOME/.config/bspwm/hotkeys &
~/.config/polybar/start.sh
