- hosts: localhost

  # roles:
  #   - common
  #   - packages
  #   - ssh
  #   - stow

  vars:
    new_hostname: "navy"

  tasks:
    - name: Set the system hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    - name: Install battery limit service
      become: yes
      ansible.builtin.copy:
        src: battery-limit.service
        dest: /etc/systemd/system/battery-limit.service
        owner: root
        group: root
        mode: '644'
      notify: Reload systemd

  handlers:
    - name: Reload systemd daemon
      listen: Reload systemd
      become: yes
      ansible.builtin.command: systemctl daemon-reload

    - name: Enable battery limit
      listen: Reload systemd
      become: yes
      ansible.builtin.systemd_service:
        name: battery-limit.service
        enabled: true


# Confirmed that this does it! Just followed the instructions from kmonad
# kmonad binary is at https://github.com/kmonad/kmonad/releases/download/0.4.4/kmonad
# needs to be placed in ~/.local/bin and chmod +x and user added to input group
# sudo groupadd --system uinput -U jstamant
# sudo echo 'KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"' > /etc/udev/rules.d/kmonad.rules
# need to stow the kmonad files, then enable user service

# systemctl --user enable --now restic-backup.timer
# /usr/local/bin/backup.sh
# /etc/restic (new folder)
# /etc/restic/  template files
# /etc/systemd/system/restic-backup.service
# /etc/systemd/system/restic-backup.timer (enable me!)
# /etc/systemd/system/restic-backup-external.service (enable me!)
# /etc/systemd/system/restic-backup-external.path (TO DELETE me!)
# jstamant@navy:~$ cat /etc/udev/rules.d/touro.rules
# ACTION=="add", SUBSYSTEM=="block", ENV{ID_FS_UUID}=="2868-4BED", TAG+="systemd", ENV{SYSTEMD_WANTS}="restic-backup-external.service"

# Also add a symlink from vim to nvim

# reaper, download a certain version and run the install?

# Install tailscale from lines found in https://tailscale.com/download/linux/fedora-2

# /etc/systemd/system/immich.service enable it and deploy it


# For jellyfin:
# /etc/containers/systemd/jellyfin.container

# Reaper was installed to ~/.local/opt/REAPER
# It added a desktop file in ~/.local/share/applications/cockos-reaper.desktop

# dnf install syncthing, then
# systemctl --user enable syncthing

# Emacs needs grammars installed
# Emacs requires package dejavu-fonts-all, probably font awesome

# need to log ansible-playbook site.yml --ask-become-pass in order to run playbook
