- hosts: localhost

  vars:
    my_user: "jstamant"
    my_hostname: "navy"
    enabled_systemd_services: []



  roles:
    - backup
    - immich

    - role: kmonad
      vars:
        kmonad_user: "{{ my_user }}"
    - role: user_environment
      vars:
        user_env_user: "{{ my_user }}"
        user_env_dotfiles_repo: "git@github.com:jstamant/dotfiles.git"



  tasks:
    - name: Set the system hostname
      become: yes
      ansible.builtin.hostname:
        name: "{{ my_hostname }}"

    - name: Install system packages
      become: yes
      ansible.builtin.package:
        state: present
        name:
          - emacs-pgtk
          - neovim

    - name: Install battery limit service
      become: yes
      ansible.builtin.copy:
        src: battery-limit.service
        dest: /etc/systemd/system/battery-limit.service
        owner: root
        group: root
        mode: '644'
      notify: Reload systemd

    - name: Install Syncthing
      become: yes
      ansible.builtin.package:
        name: syncthing
        state: present

    - name: Enable Syncthing
      become: yes
      become_user: "{{ my_user }}"
      systemd:
        name: syncthing.service
        enabled: true
        scope: user



  handlers:
    - name: Reload systemd daemon
      listen: Reload systemd
      become: yes
      ansible.builtin.command: systemctl daemon-reload

    - name: Enable battery limit
      listen: Reload systemd
      become: yes
      ansible.builtin.systemd_service:
        name: battery-limit.service
        enabled: true

    - name: Reload udev rules
      listen: Reload udev
      become: yes
      command: udevadm control --reload-rules



  post_tasks:
    - name: Enable systemd services
      become: yes
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
      loop: "{{ enabled_systemd_services }}"


# reaper, download a certain version and run the install?

# Install tailscale from lines found in https://tailscale.com/download/linux/fedora-2

# For jellyfin:
# /etc/containers/systemd/jellyfin.container

# Reaper was installed to ~/.local/opt/REAPER
# It added a desktop file in ~/.local/share/applications/cockos-reaper.desktop

# Emacs needs grammars installed
# Emacs requires package dejavu-fonts-all, probably font awesome
