- hosts: localhost

  roles:
    - backup
  #   - common
  #   - packages
  #   - ssh
  #   - stow

  vars:
    new_hostname: "navy"
    enabled_systemd_services: []

  tasks:
    - name: Set the system hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ new_hostname }}"

    - name: Install battery limit service
      become: yes
      ansible.builtin.copy:
        src: battery-limit.service
        dest: /etc/systemd/system/battery-limit.service
        owner: root
        group: root
        mode: '644'
      notify: Reload systemd

  handlers:
    - name: Reload systemd daemon
      listen: Reload systemd
      become: yes
      ansible.builtin.command: systemctl daemon-reload

    - name: Enable battery limit
      listen: Reload systemd
      become: yes
      ansible.builtin.systemd_service:
        name: battery-limit.service
        enabled: true

    - name: Enable systemd services
      listen: Reload systemd
      become: yes
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        enabled: true
      loop: "{{ enabled_systemd_services }}"

    - name: Reload udev rules
      listen: Reload udev
      become: yes
      command: udevadm control --reload-rules


# Confirmed that this does it! Just followed the instructions from kmonad
# kmonad binary is at https://github.com/kmonad/kmonad/releases/download/0.4.4/kmonad
# needs to be placed in ~/.local/bin and chmod +x and user added to input group
# sudo groupadd --system uinput -U jstamant
# sudo echo 'KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"' > /etc/udev/rules.d/kmonad.rules
# need to stow the kmonad files, then enable user service

# Also add a symlink from vim to nvim

# reaper, download a certain version and run the install?

# Install tailscale from lines found in https://tailscale.com/download/linux/fedora-2

# /etc/systemd/system/immich.service enable it and deploy it


# For jellyfin:
# /etc/containers/systemd/jellyfin.container

# Reaper was installed to ~/.local/opt/REAPER
# It added a desktop file in ~/.local/share/applications/cockos-reaper.desktop

# dnf install syncthing, then
# systemctl --user enable syncthing

# Emacs needs grammars installed
# Emacs requires package dejavu-fonts-all, probably font awesome
